### ISSUE TITLE
建议增加idea新建SpringMVC的方法

### ISSUE THREAD

**Issue by sky5454** [skyline75489/Heart-First-JavaWeb#6]
例如
[IDEA建立Spring MVC Hello World 详细入门教程](https://www.cnblogs.com/wormday/p/8435617.html)

当然，我不是博主...

**Comment by skyline75489** [comment]
大体看了下，感觉内容基本上都覆盖了...如果感觉有可以补充的，欢迎 PR~

**Comment by sky5454** [comment]
希望在这个Gitbook右上角增加一个Github链接，不然贡献基本没有

**Comment by skyline75489** [comment]
是个好建议，Introduction 部分其实写了链接了，我还真没研究过能不能在右上角也加上 Github 链接。

不过其实开源项目本来就是没有那么多人会 PR 的，我已经习惯了 😄
