### ISSUE TITLE
第 8 的

### ISSUE THREAD

**Issue by sky5454** [skyline75489/Heart-First-JavaWeb#8]
(https://skyline75489.github.io/Heart-First-JavaWeb/8-Intro-Spring-Bean.html)  

"和一个依赖 Person 的 Service 类："
这一段下面的代码有问题，MyService 并不在这个包内，而是在上一级的包里

**Comment by skyline75489** [comment]
代码仅供参考，本意并不希望读者直接把代码 copy 过来去跑，而是自己手打。包名在这里重要性就不是很大了

**Comment by sky5454** [comment]
还是说明一下“代码仅供参考”吧，毕竟文章是给初学者的

**Comment by skyline75489** [comment]
只是给 Java Web 的初学者，而不是纯 Java。还是需要有一定 Java 基础的。这个在一开始有介绍
